import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ClerkProvider, SignedIn, SignedOut } from '@clerk/nextjs'
import SignUpOrIn from './sign-up/page'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <SignedOut>
          <SignUpOrIn />
        </SignedOut>
        <SignedIn>
          <body className={inter.className}>{children}</body>
        </SignedIn>
      </html>
    </ClerkProvider>
  )
}
